# Generated by Django 5.2.9 on 2026-01-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_chatbottraining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='register_number',
            field=models.CharField(help_text='Registration number', max_length=20, null=True),
        ),
    ]
